theme = Catppuccin Mocha
background = 181825
foreground = cdd6f4
font-family = JetBrainsMono Nerd Font
font-size = 15
window-padding-x = 0
window-padding-y = 0
window-decoration = false
window-title-font-family = JetBrainsMono Nerd Font
confirm-close-surface = false
